/// @file      Games.inc
/// @author    BOURAOUI Al-Moez L.A
/// @date      Created at 2022-07-14 20:17:56 +0200
/// @copyright Copyright (c) 2022

#include "games/EventSystem.pwn"
#include "games/FightClub.pwn"
#include "games/Hunter.pwn"
#include "games/MiniGame.pwn"
#include "games/PaintBall.pwn"
#include "games/RaceEvent.pwn"
#include "games/TreasureHunt.pwn"
#include "games/DuelEvent.pwn"
#include "games/FallOut.pwn"
//#include "games/festival/Festival.inc"
