/// @file      Constants.inc
/// @author    BOURAOUI Al-Moez L.A
/// @date      Created at 2022-07-14 14:22:02 +0200
/// @copyright Copyright (c) 2022

#include "const/version.def"
#include "const/Abreviations.def"
#include "const/Admin.def"
#include "const/Color.def"
#include "const/Max.def"
#include "const/Misc.def"
#include "const/ModelSelection.def"
#include "const/ServerConfig.def"
#include "const/Sql.def"
#include "const/Iterator.def"
#include "const/Player.def"
