#!/bin/bash

PID=firewall.pid
DEAMON_LOG=firewall.log
COMMAND="./firewall.py"

status()
{
    echo
    echo "==== Server status ===="

    if [ -f $PID ]
    then
        echo
        echo "Pid file: $( cat $PID ) [$PID]"
        echo
        ps -ef | grep -v grep | grep $( cat $PID )
    else
        echo
        echo "Server is down (No Pid file)"
    fi
}

start()
{
    if [ -f $PID ]
    then
        echo
        echo "Already started. PID: [$( cat $PID )]"
    else
        echo "==== Starting server ===="
        echo "[$(date '+%Y-%m-%d %T')] [Daemon] Starting Server" >>$DEAMON_LOG
        touch $PID
        if nohup $COMMAND >>$DEAMON_LOG 2>&1 &
        then echo $! >$PID
             echo "Done."
        else echo "Error... "
             /bin/rm $PID
        fi
    fi
}

kill_cmd()
{
    echo "==== Killing server ===="

    if [ -f $PID ] ; then

        LIST=`ps -ef | grep -v grep | grep $( cat $PID ) | awk '{print $2}'`

        if [ "$LIST" ] ; then
            echo
            echo " List of tasks to be killed:"
            ps -ef | grep -v grep | grep $( cat $PID )
            echo
            echo $LIST | xargs kill -9

            while true
            do
                sleep 1

                LIST=`ps -ef | grep -v grep | grep $( cat $PID ) | awk '{print $2}'`

                if [ "$LIST" ] ; then
                    echo -n .
                else
                    break
                fi
            done

            /bin/rm $PID

            echo
            echo "All killed..."
            echo "[$(date '+%Y-%m-%d %T')] [Daemon] Server Killed" >>$DEAMON_LOG
            echo
        else
            /bin/rm $PID
            echo "Process is already stopped."

        fi
    else
        echo "No pid file. Already stopped?"
    fi
}

stop()
{
    echo "==== Stop server ===="

    if [ -f $PID ] ; then

        LIST=`ps -ef | grep -v grep | grep $( cat $PID ) | awk '{print $2}'`

        if [ "$LIST" ] ; then
            echo
            echo " List of tasks to be stopped:"
            ps -ef | grep -v grep | grep $( cat $PID )
            echo
            echo $LIST | xargs kill


            while true
            do
                sleep 1

                LIST=`ps -ef | grep -v grep | grep $( cat $PID ) | awk '{print $2}'`

                if [ "$LIST" ] ; then
                    echo -n .
                else
                    break
                fi
            done

            /bin/rm $PID

            echo
            echo "All stopped..."
            echo "[$(date '+%Y-%m-%d %T')] [Daemon] Server Stopped" >>$DEAMON_LOG
            echo
        else
            /bin/rm $PID
            echo "Process is already stopped."

        fi
    else
        echo "No pid file. Already stopped?"
    fi
}

case "$1" in
    'start')
            start
            ;;
    'kill')
            kill_cmd
            ;;
    'stop')
            stop
            ;;
    'restart')
            stop ; echo "Sleeping..."; sleep 1 ;
            start
            ;;
    'status')
            status
            ;;
    *)
            echo
            echo "Usage: $0 { start | stop | kill | restart | status }"
            echo
            exit 1
            ;;
esac

exit 0

