/// @file      Inventoy.pwn
/// @author    BOURAOUI Al-Moez L.A
/// @date      Created at 2022-07-14 14:22:02 +0200
/// @copyright Copyright (c) 2022


enum
{
    ITEM_WEAPON,
    ITEM_SELLGUN,
    ITEM_MATERIALS,
    ITEM_WEED,
    ITEM_COCAINE,
    ITEM_HEROIN,
    ITEM_PAINKILLERS,
    ITEM_SEEDS,
    ITEM_CHEMICALS,
    ITEM_CASH,
    ITEM_BACKPACK,
    ITEM_SKIN,
    ITEM_GSELLGUN,
    ITEM_DIAMONDS
};

enum
{
    CAPACITY_MATERIALS,
    CAPACITY_WEED,
    CAPACITY_COCAINE,
    CAPACITY_HEROIN,
    CAPACITY_PAINKILLERS,
    CAPACITY_SEEDS,
    CAPACITY_CHEMICALS,
    CAPACITY_GASCAN
};

enum
{
    STASH_CAPACITY_CASH,
    STASH_CAPACITY_MATERIALS,
    STASH_CAPACITY_WEED,
    STASH_CAPACITY_COCAINE,
    STASH_CAPACITY_HEROIN,
    STASH_CAPACITY_PAINKILLERS,
    STASH_CAPACITY_WEAPONS
};

enum
{
    GANGWEAPON_9MM,
    GANGWEAPON_SDPISTOL,
    GANGWEAPON_DEAGLE,
    GANGWEAPON_SHOTGUN,
    GANGWEAPON_TEC9,
    GANGWEAPON_UZI,
    GANGWEAPON_MP5,
    GANGWEAPON_AK47,
    GANGWEAPON_RIFLE,
    GANGWEAPON_M4,
    GANGWEAPON_SPAS12,
    GANGWEAPON_SNIPER
};

new gSeedsStock = 200;
new gCocaineStock = 100;
new gChemicalsStock = 50;
new Text3D:gSeedsStockText;
new Text3D:gCocaineText;
new Text3D:gChemicalsStockText;
