/// @file      Models.inc
/// @author    BOURAOUI Al-Moez L.A
/// @date      Created at 2022-07-14 20:17:56 +0200
/// @copyright Copyright (c) 2022

#include "models/Admin.pwn"
#include "models/AdminReport.pwn"
#include "models/Atm.pwn"
#include "models/Business.pwn"
#include "models/ClothingInfo.pwn"
#include "models/Coords.pwn"
#include "models/Entrance.pwn"
#include "models/Faction.pwn"
#include "models/Gang.pwn"
#include "models/Garage.pwn"
#include "models/Gates.pwn"
#include "models/Global.pwn"
#include "models/Hospital.pwn"
#include "models/House.pwn"
#include "models/Inventoy.pwn"
#include "models/Job.pwn"
#include "models/Land.pwn"
#include "models/Locker.pwn"
#include "models/PlayerData.pwn"
#include "models/ObjectInfo.pwn"
#include "models/Payphone.pwn"
#include "models/PrisonInfo.pwn"
#include "models/Property.pwn"
#include "models/VehicleInfo.pwn"
